# Dev local : http://localhost:1313/
# En production, GitHub Actions surcharge avec --baseURL (voir .github/workflows/hugo.yml)
baseURL = 'http://localhost:1313/'
languageCode = 'fr-fr'
title = 'Portfolio - Benoit Paquier - Diplôme universitaire Fabmanager'
defaultContentLanguage = 'fr'
disableKinds = ['taxonomy', 'term']

[outputs]
  home = ['HTML', 'RSS']

[params]
  author = 'Benoit Paquier'
  description = 'Portfolio — Fabmanager
  github = 'https://github.com/fuuuzz'
  email = 'benoit.paquier@ik.me'
  all_projects_url = 'https://trite-cobra-9df.notion.site/311226f095eb8060b13dc57bb50a463d?v=311226f095eb8087a47a000c4fef0ed9'
  journal_url = 'https://trite-cobra-9df.notion.site/Journal-de-bord-30b226f095eb805eb53fc9c1395738d8'

  [params.profile]
    name = 'Benoit Paquier'
    title = 'Étudiant Fabmanager'
    image = 'images/profile.webp'
    text = '''
En reconversion vers le métier de fabmanager, je combine une solide expérience en développement web
(depuis 2015, en France et au Canada) et en formation (en tant que formateur en au métier de
développeur web). Titulaire du Diplôme Universitaire Fabmanager –
Techniques de facilitation & de fabrication numérique, je mets à profit mes compétences techniques,
mon autonomie et mon sens pédagogique pour accompagner les utilisateurs des fablabs et leur projets.
Rigoureux, communicant et passionné par la transmission, je m’engage à créer des environnements de
travail stimulants et inclusifs.
'''

[caches]
  [caches.images]
    dir = ':cacheDir/images'
