[build.environment]
DART_SASS_VERSION = "1.101.0"
GO_VERSION = "1.26.4"
HUGO_VERSION = "0.163.3"
NODE_VERSION = "24.16.0"
TZ = "Europe/Oslo"

[build]
publish = "public"
command = """\
  git config --global core.quotepath false && \
  hugo build --gc --minify --baseURL "${URL}"
  """